name: Database Migration CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get version
      id: get_version
      run: |
        cd cicd/migrations/taxishop/
        version=$(./read_project_version.sh)
        echo "Current version is $version"
        echo "Current tag is $(git tag)"
        echo "PROJECT_VERSION=$version" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        current_tag=$(git describe --tags)
        git tag -f $PROJECT_VERSION
        diff_tags=$(./get_git_tag_diff.sh $current_tag $PROJECT_VERSION)
        
        cd cicd/migrations/taxishop/
        for tag in $diff_tags; do
          if [[ "$tag" > "$current_tag" ]]; then
            mode="migrate"
          else
            mode="revert"
          fi
          python -m src.db.migration_handler --version $tag --mode $mode --dbname taxi --print-only
        done
